[package]
name = "pathtracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.14.0"
env_logger = "0.11.4"
image = "0.25.2"
log = "0.4.22"
nalgebra = "0.33.0"
